### ISSUE TITLE
dynamic return values

### ISSUE THREAD

**Issue by nmushegian** [dapphub/ds-proxy#12]
byzantium fork allows dynamically sized return values

**Comment by rainbreak** [comment]
@gbalabasquer be aware of this

**Comment by nmushegian** [comment]
@NiklasKunkel too

**Comment by Jake-Gillberg** [comment]
Would the proxy be able to compute the return size of the function it is `delegatecall`ing?

**Comment by rainbreak** [comment]
@Jake-Gillberg yes, RETURNDATASIZE and RETURNDATACOPY can be used to access the full return data. We should probably update ds-proxy now to return `bytes` rather than `bytes32` (or as well as, if backwards compat is important).

**Comment by NiklasKunkel** [comment]
If this isn't high priority I'd like to take this one once I finish up with
Oracles for MCD.

**Comment by gbalabasquer** [comment]
We should probably upgrade this before releasing the new CDP Dashboard as we avoid post migration. I'll take a look and check with you @NiklasKunkel

**Comment by gbalabasquer** [comment]
This was done.
