### ISSUE TITLE
Transferring ownership with setOwner doesn't update registry

### ISSUE THREAD

**Issue by jmlag** [dapphub/ds-proxy#28]
Is this intentional?

**Comment by gbalabasquer** [comment]
`ProxyRegistry` is a wrapper contract for `DSProxyFactory` which adds some extra logic. It doesn't belong to the dapphub set of contracts.
`DSProxy` knows nothing about the registry, that is why it can't update the registry. It is not a bug.

**Comment by paulrberg** [comment]
I think that this could be closed now.
